# PostgreSQL configuration for Entmoot
#
# For Docker development, ensure you have the services running:
#   docker-compose up -d postgres
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: entmoot_development

test:
  <<: *default
  database: entmoot_test

production:
  <<: *default
  database: entmoot_production
  username: <%= ENV["ENTMOOT_DATABASE_USER"] %>
  password: <%= ENV["ENTMOOT_DATABASE_PASSWORD"] %>
  host: <%= ENV["ENTMOOT_DATABASE_HOST"] %>
